### ISSUE TITLE
Update fields

### ISSUE THREAD

**Issue by jesusvilla** [formly-js/vue-formly#38]
When the fields are modified, it does not respect the required validation, even though the new field is required, it is detected as valid. This is because the model of the new field is not defined ([https://github.com/formly-js/vue-formly/blob/master/src/components/FormlyField.js#L49](url)) which is solved by defining it as an empty string ([https://github.com/formly-js/vue-formly/blob/master/src/components/FormlyForm.js#L78](url)).

**Comment by matt-sanders** [comment]
Can you provide an example of the issue you're having? Sounds like you can/should define the field on the model.

**Comment by jesusvilla** [comment]
[https://codepen.io/jvillanueva/pen/PyxPZP](url)
Steps to reproduced
1. Click on submit button. Result: 'State valid: true'. It's correct
2. Click on button 'Update Fields'.
3. Click on submit button. Result: 'State valid: true'. It's incorrect

**Comment by matt-sanders** [comment]
Hmm, I'm not sure this is really the best way to approach your issue. From what I can see you're completely replacing the fields. I would do one of three things depending on what you're actually trying to achieve:

1. to hide/show fields, use [Conditional Rendering](https://matt-sanders.gitbooks.io/vue-formly/content/v/2.0/how_to_use/conditional-rendering.html)
2. to display a new form, maybe just actually have a different form with different fields and show it with a v-if condition
3. if you're really set on this approach, use the `:key` field on the `formly-form` element to re-render the field whenever the fields change. You need this because there is a bunch of logic that goes on when a form is mounted. See: https://codepen.io/anon/pen/NOEorm

**Comment by jesusvilla** [comment]
@matt-sanders 
The only thing I want to achieve is that when loading a new form, validate correctly. For now I have to uncomment line 13 of the copeden ([https://codepen.io/jvillanueva/pen/PyxPZP](url)). Although the correct thing would be to add this lines, before changing the new fields:
```javascript
this.model = {};
this.form = {
  $errors: {}
};
this.fields = [...]
```
With this I avoid assigning your computed variable: `fieldKeys`

**Comment by matt-sanders** [comment]
If you're aim is to load a new form, I would try to do just that, actually have a completely different form that loads when you want it to, instead of changing the content of that form. You could even share the same model if you wanted, e.g:
```vue
<formly-form v-if="formToRender === 'form1'" :model="model" :form="form1" :fields="fields1"></formly-form>
<formly-form v-if="formToRender === 'form2'" :model="model" :form="form2" :fields="fields2"></formly-form>
```
```js
data(){ 
   return {
      formToRender: 'form1',
      model: {
         firstField: '',
         secondField: ''
      },
      form1: {},
      form2: {},
      fields1: [{key: 'firstField', type: 'input'}],
      fields2: [{key: 'secondField', type: 'input'}]
   }
}
```
I get that you just want to change the fields, but I think you're probably going about it the wrong way. Simply changing the fields isn't the correct approach here, and unless there's something I'm not understanding I think you should be able to use some of the given solutions in your project.

Happy to keep discussing this if you're still having issues, otherwise I'll close it. If you want to send me a more comprehensive example of what you're doing feel free and I'll take a look at it.

**Comment by jesusvilla** [comment]
I'm working on a project, the truth is that your library is great for it, even better than [https://github.com/vue-generators/vue-form-generator](url) since it allows me to customize it my way, only when I need to generate a form from an ajax, the 'required' validations do not work because these new fields are not recognized. For my part I already managed the solution, but I had to read its source code to do it, it was enough to execute again lines 77 to 79 ([https://github.com/formly-js/vue-formly/blob/master/src/components/FormlyForm.js#L78](url)).

**Comment by matt-sanders** [comment]
Aah, I see, well, I'm glad you found a solution and that you like Vue Formly :)
