### ISSUE TITLE
Are nested array of fields or fieldgroups supported?

### ISSUE THREAD

**Issue by shubhangisa** [formly-js/vue-formly#39]
I'm using vue-formly in my project, but I need vue-formly support for nested array of fields or fieldGroups.
Currently, vue-formly reads array of fields but not nested arrays.
Is this supported?

**Comment by matt-sanders** [comment]
Are you after repeater functionality? Currently this isn't supported 'out-of-the-box' by vue formly but this is possible by creating your own custom field which "repeats" your model. I will try and get an example up at some point with some more details. I haven't implemented this natively into Vue Formly because it seems to me that there are a lot of ways that people expect this to be used/would want to configure it, so instead of supporting each different one, or locking users into one way in specific, I think it'd be better to let users build their own. I'll post a gist soon.

**Comment by matt-sanders** [comment]
Here's a gist with a sample repeater field. When using it you can add a `subForm` parameter to your field definition. E.g:

```js
fields: [{
   key: 'someRepeatedField',
   type: 'repeater',
   subForm: {
      fields: [{
         key: 'name',
         type: 'input'
       }]
   },
   subModel: {
      name: ''
   }
}
```
