### ISSUE TITLE
Error in callback for watcher when dynamically load model

### ISSUE THREAD

**Issue by shsmad** [formly-js/vue-formly#40]
Hi!

I have an app:
```
new Vue({
    el: '#app',
    data: { forms: { mainform: {} } }
});
```
and component
```
<mainform v-bind:form="forms.mainform"></mainform>
```
which is:
```
{
    props: ['form'],
    template: `
    <form v-if="validForm" ref="mainForm">
        <formly-form :form="form.form" :model="form.model" :fields="form.fields"></formly-form>
        <button>Submit</button>
    </form>`,
   computed: {
       validForm: function(){ return this.form.fields; }
   },
}
```

Then in some part of code I do:
```
axios.get('/api/forms/' + formid).then(function(resp){
    Vue.set(vm.$root.forms, 'mainform', resp.data);
});
```

Server reply is in json:
```
{
    'model': { 'name': 'qwe',},
    'form': {},
    'fields': [{
        'key': 'name',
        'type': 'input',
        'required': True,
        'templateOptions': {
            'label': 'label for name',
        }
    }]
}
```

The first time I do axios.get form is set up correct, but when I try to update it to another form from server I get an error:

```
[Vue warn]: Error in callback for watcher "form.$errors": "TypeError: can't convert undefined to object"

found in

---> <FormlyForm>
       <Mainform>
         <Root> vue.js:597:7
TypeError: "can't convert undefined to object"
	created http://localhost:3000/static/vendor/vue-formly/vue-formly.js:7:4424
	run http://localhost:3000/static/vendor/vue/vue.js:3231:11
	flushSchedulerQueue http://localhost:3000/static/vendor/vue/vue.js:2981:5
	nextTick http://localhost:3000/static/vendor/vue/vue.js:1839:9
	flushCallbacks http://localhost:3000/static/vendor/vue/vue.js:1760:14
```

**Comment by matt-sanders** [comment]
Hmm, this sounds similar to #38 if it were me I would try a few different things:

1. force the form to re-render when you change the fields. You could do something like using a dynamic key, seen here: https://codepen.io/anon/pen/NOEorm which means that whenever you change the fields it will re-run all the startup methods that set the required data
2. use a `v-if="!loading"` statement so that the form isn't trying to process things while you change it's data.
3. instead of overwriting the fields etc, use a different form, e.g:
```vue
<template>
<mainform :form="forms[currentForm]"></mainform>
</template>
<script>
export default {
   data(){
      return {
         forms: {
            mainForm: {...}
         },
         currentForm: 'mainForm'
      }
   },
   methods: {
      loadNewForm(newForm){
         axios.get(`/someroute/${newForm}`)
            .then(response => {
               this.$set(this.forms, newForm, response.data)
               this.currentForm = newForm
            })
      }
   }
}
</script>
```
If you use number 3, then you wouldn't have to use number 1, instead make the key something like: `form-${formKey}` or something like that. 
Does that make sense? Hopefully it helps. I've just assumed a few parts of functionality ( such as loading a new form ) but that might help you to re-work it for your needs.

**Comment by shsmad** [comment]
Thanx!

For me 1 + 3 methods worked together:
1. I use `this.forms` as a dict for all forms
2. I use `this.currentForm` as a `:key` for `<formly-form>`
3. When fetched from server I update only `this.forms[this.currentForm].fields` (instead of fields + form + model) if the form already exists in `this.forms`

Though if I skip 2 or 3 step I get an error
