### ISSUE TITLE
Dynamic forms in formly angualr based on array length

### ISSUE THREAD

**Issue by ACJamesX** [formly-js/vue-formly#53]
Hi need help in creating dynamic forms based on my cards array length
below is my template code where i have added the formly tag.
<div fxFlex="30" *ngFor="let card of cards; let cardIndex = index" class="card">
  <div fxLayout="row">
    <div fxFlex="85" style="margin-bottom: 1rem; margin-top: 10px">
      <span class="chip" *ngIf="card"> {{ card.product.name }} </span>
    </div>
    <div fxFlex="10">
      <button
        mat-button
        class="primary btn-delete"
        (click)="deleteCard(cardIndex)"
      >
        <mat-icon style="color: #ff6262">delete</mat-icon>
      </button>
    </div>
  </div>
  <div>
    <ng-container>
      <div>
        <div fxlayout="row">
          <div fxFlex="100">
            <formly-form
              [model]="model"
              [fields]="fields"
              [options]="options"
              [form]="form"
            ></formly-form>
          </div>
        </div>
      </div>
    </ng-container>
  </div>
</div>
What is happening here is that same form is being used in my all cards which creates issue
for eg when i select the dropdown in one card it gets opened in the other card too. I feel this is because a single form is repeated in all my cards , so need help to fix this.
PS: I am using Angular material
THANKS IN ADVANCE

**Comment by ACJamesX** [comment]
@juristr
@aitboudad

**Comment by matt-sanders** [comment]
Hey there

This repo is unmaintained at the moment and it's been years since I've looked at it, so I'm speaking from memory here, but a couple of things jumped out at me.

Firstly, you mentioned you're using angular material but this is the library for Vue Formly. Are you definitely using Vue Formly or Angular Formly?

If you have the same form for multiple cards, you should probably try and separate that, so that you're using different instances of the same form. Alternatively, give your fields a unique name based on the card, probably by issuing some sort of ID.

This was made for Vue 2, so if none of the above work, maybe it's a Vue 2 vs 3 issue.

See how you get on with those, hopefully something there works for you!

**Comment by ACJamesX** [comment]
Hi @matt-sanders 
im using Angular Formly

**Comment by matt-sanders** [comment]
Ah ok, try your luck over at [that repo](https://github.com/formly-js/angular-formly/issues)
